### ISSUE TITLE
Can the training code run?

### ISSUE THREAD

**Issue by Yuanhong200727** [Sirui-Xu/DuMMF#3]
Your work is awesome, sir. And I want to train it by myself. Can I run the training directly by running train_diffusion.py? And can you provide your detailed env? I've tried many times to run the script, but all failed.

**Comment by Sirui-Xu** [comment]
Hi,

I think so. Let me check my previous environment. I'll get back to you in the next few days.

**Comment by Sirui-Xu** [comment]
May I ask what is the fault you are experiencing?

**Comment by Yuanhong200727** [comment]
Sorry for the late reply.When I installed all the env I need and run the train_diffusion.py, the error was this:
```
Traceback (most recent call last):
  File "train_diffusion.py", line 514, in <module>
    train_dataset = Dataset(mode = 'train', past_len=args.past_len, future_len=args.future_len, sample_rate=args.sample_rate)
  File "/root/DuMMF/data_amass.py", line 48, in __init__
    for iii, each in enumerate(os.listdir(poses_path_A)):
FileNotFoundError: [Errno 2] No such file or directory: './mocap/CMU/18_19_Justin/'
```
It seems that some dataset file was missed.Then I downloaded the Mocap-CMU dataset and ran the several scripts in mocap directory, only getting these files:
```
discriminator_3_120_mocap.npy
one_test_4seconds_30.npy
one_train_4seconds_30.npy
test_3_120_mocap.npy
train_3_120_mocap.npy
two_test_4seconds_2.npy
two_train_4seconds_2.npy
```
by the way, there may be some mistakes in preprocess_amass.py.In line 39 the variable  'joints' and 'motions' is used without declared, but in preprocess_mocap.py it is good.

How can I get the directory './mocap/CMU/18_19_Justin/'?
And here are other required files like './mocap/body_models/smplh/neutral/model.npz','./mocap/body_models/V02_05'.

Could you tell me how to get this files or upload them using google drive or other ways?I'll really appreciate it.Thanks a lot

**Comment by Sirui-Xu** [comment]
Hi,

I added all my processed CMU Mocap data at https://drive.google.com/file/d/1p43mhdpEh5tvl04B5XeYbg76Cr3KCRuT/view?usp=sharing, you can download it and directly put them on './mocap'

For the SMPLX body model, you can download it from https://smpl-x.is.tue.mpg.de/, and put it under './mocap/body_models/'

please feel free to contact me if you have any further question.

Thanks!

**Comment by Yuanhong200727** [comment]
Hey, I've ran the training code successfully. But in this line:
`from render.mesh_viz import visualize_body_multi
`
It seems that there is not a file called mesh_viz.py in the code provided.

**Comment by fancy1223** [comment]
Hi, Can you provide the link for this file? AssertionError: No checck points found at ./mocap/body_models/V02_05/snapshots. Thanks!
