### ISSUE TITLE
something about condition and social intents.

### ISSUE THREAD

**Issue by Yuanhong200727** [Sirui-Xu/DuMMF#5]
I have some questions about condition and social intents.
## condition
About the condition to generate future motions in the code. In my opinion, it should be the motion sequence with the length of past_len attribute of the input data(or gt in code). However, in this function
```
def _get_embeddings(self, data, device=None):
        if device:
            body_pose = data['poses'].float().to(device) # BxMxTxD
            body_trans = data['trans'].float().to(device)  # BxMxTx3

        else:
            body_pose = data['poses'].float() # BxMxTxD
            body_trans = data['trans'].float() # BxMxTx3

        B, M, T, _ = body_pose.shape
        body_pose = matrix_to_rotation_6d(axis_angle_to_matrix(body_pose.view(B, M, T, -1, 3))).view(B, M, T, -1)
        body_trans_start = body_trans[:, :, 0:1, :]#get the first frame
        body_pose_start = body_pose[:, :, 0:1, :6]#get the first frame
        body_trans = body_trans - body_trans_start
        body_start = torch.cat([body_trans_start, body_pose_start], dim=3)
        embedding = self.globalEmbedding(body_start).unsqueeze(3).repeat(1, 1, self.args.past_len+self.args.future_len, self.args.num_queries, 1).permute(2, 0, 3, 1, 4).contiguous().view(self.args.past_len+self.args.future_len, B*self.args.num_queries*M, -1)
        # print('model convert', obj_angles[0])
        gt = torch.cat([body_pose, body_trans], dim=3)
        # B N M T D -> T BNM D
        gt = gt.unsqueeze(1).repeat(1, self.args.num_queries, 1, 1, 1).permute(3, 0, 1, 2, 4).view(T, B*self.args.num_queries*M, -1)
        return embedding, gt
```
and then:
 ```
def _common_step(self, batch, batch_idx, mode):
      embedding, gt = self.model._get_embeddings(batch)
      # [t, b, n] -> [bs, njoints, nfeats, nframes]
      gt = gt.permute(1, 2, 0).unsqueeze(1).contiguous()
      model_kwargs = {'y': {'cond': embedding}}
      model_kwargs['y']['inpainted_motion'] = gt
      model_kwargs['y']['inpainting_mask'] = torch.ones_like(gt, dtype=torch.bool,device=device)  # True means use gt motion
      model_kwargs['y']['inpainting_mask'][:, :, :, self.args.past_len:] = False  # do inpainting in those frames
```

It seems that the embedding only use the first frame of the past_len, and repeating to meet the shape of gt.
Why not use the full past_len?  And I'm also wondering why just only use the first six elements in `body_pose_start = body_pose[:, :, 0:1, :6]` instead of the full body pose?
## intents
In paper, after embedding the human pose, it sample intents from continuous intents and discrete intents. Where is the code about this process? 
Thanks!

**Comment by Sirui-Xu** [comment]
Hi @Yuanhong200727 ,

Sorry for the delay. [The adding of local intent] (https://github.com/Sirui-Xu/DuMMF/blob/main/DuMMF/SubLayers.py#L429), and [the adding of global intent](https://github.com/Sirui-Xu/DuMMF/blob/main/DuMMF/SubLayers.py#L452) are in the architecture, for which the local one is discrete and learnable. For the diffusion baseline in the paper, it is already introducing continuous intent because of the sampling of noise.

Feel free to reach out if you have further questions!

Best,
Sirui

**Comment by Yuanhong200727** [comment]
> Hi @Yuanhong200727 ,
> 
> Sorry for the delay. [The adding of local intent](https://github.com/Sirui-Xu/DuMMF/blob/main/DuMMF/SubLayers.py#L429) (named as query in the code), and [the adding of global intent](https://github.com/Sirui-Xu/DuMMF/blob/main/DuMMF/SubLayers.py#L452) (named as memory in the code) are in the architecture, for which the local one is discrete and learnable. For the diffusion baseline in the paper, it is already introducing continuous intent because of the sampling of noise.
> 
> Feel free to reach out if you have further questions!
> 
> Best, Sirui

Thanks! I'll check it. And how about the condition question?

**Comment by Sirui-Xu** [comment]
Great question. If I remember correctly, Such a condition (using the first frame as global intent) is the same as prior work [MRT](https://jiashunwang.github.io/MRT/) and we just blindly adopted it for a fair comparison. Note that we still have the whole past sequence being injected into the diffusion process via model_kwargs['y']['inpainted_motion'] and model_kwargs['y']['inpainting_mask'].
